### ISSUE TITLE
Crash with Create contraptions

### ISSUE THREAD

**Issue by izzyjeezy** [RelativityMC/C2ME-neoforge#37]
**Describe the bug**
Crash with Create contraptions

**To Reproduce**
1. Make Elevator with Contraption Controls
2. Right click on Elevator Pulley
3. Crash appears

**Expected behavior**
Create elevator

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.21.1
 - Mod version: 0.3.0+alpha.0.85 devbuild

**Crash reports / logs**
https://pastebin.com/Pk9ATncQ

**Other mods**
Only C2ME and Create

**Checklist**

 - [x] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by EvieTheOwl** [comment]
Did you try with just Create installed?

**Comment by izzyjeezy** [comment]
> Did you try with just Create installed?

Without C2ME (only Create) everything works fine

**Comment by EvieTheOwl** [comment]
Quick question but do you have `fixes.enforceSafeWorldRandomAccess` disabled in the config? If not that might fix the crash. I don't think it can fix the problem though.

**Comment by Mrnar1s** [comment]
Had this same issue, however, i was on a server, while C2ME was installed in both the client and the server, me and my friend would crash, the server would not, removing C2ME from the client made it work, even tho we still had the mod on the server. So it seems to be a client side issue

**Comment by EvieTheOwl** [comment]
I think this is fixed in the latest version of C2ME. Definately try it to see.

**Comment by Mrnar1s** [comment]
> I think this is fixed in the latest version of C2ME. Definately try it to see.

It was not fixed. The issue is still present in the latest version of C2ME and Create
